### ISSUE TITLE
Wrong file encoding

### ISSUE THREAD

**Issue by ArthurVinbeau** [RubenHuizenga/SuperMissionStats#36]
Hello,

The stats file are saved in UTF-16 LE on my computer which prevents them from being read by the super mission stats viewer that can only read UTF-8 files.

The mod is installed ingame with mod.io on a steam client on a French windows 11.

I did a workaround by reading bytes in rust and handling the conversion in TS but it is not very elegant.

Do you have any idea why it is encoding in UTF-16 LE or any way I could help you diagnose the issue?

**Comment by RubenHuizenga** [comment]
I do apologise for the late response, I've been busy with work and GitHub decided to not notify me of this issue...

I have looked into it a little and found out that it saves it as UTF-16LE when there is a character from a non-latin alphabet in the file. So it fails with error cubes but also languages like Chinese. 

I don't think there is much to fix on this side of the issue, as I'm just using the build in write to file function. I should make a fix in the viewer itself to allow it to convert those files to UTF-8. If there is any Rust devs who can lend me a hand with that that would be wonderful!

**Comment by RubenHuizenga** [comment]
Alrighty, I just released a [new version](https://github.com/RubenHuizenga/super-mission-stats-viewer/releases) of the viewer which should work with UTF-16 encoded fiels
